-----TO SEE ALL THE INFROMATION IN TABLES WE INSERTED------

SELECT*FROM USERS ---USERS TABLE ALL DATA IS SHOWN
SELECT*FROM ORDERS ---ORDERS TABLE ALL DATA IS SHOWN
SELECT*FROM PRODUCTS ----PRODUCTS TABLE ALL DATA IS SHOWN
SELECT* FROM ORDER_ITEMS --- ORDER_ITEMS ALL THE DATA IS SHOWN

----QUERY TO SHOW THE USERID,USERNAME,EMAIL FOR WHOSE SHIPPING ADDRESS IS FROM TRIPURA?
SELECT userID,username,email,shipping_address from USERS 
WHERE shipping_address like 'TRIPURA'

----QUERY TO SHOW WHOSE TOTAL AMOUNT IS BETWEEN 2000 AND 5000?
SELECT userID,order_status,total_amount from ORDERS
WHERE total_amount BETWEEN 2000 AND 5000

----QUERY TO SHOW WHOSE USERNAME STARTING LETTER IS "R"?
SELECT username,email from USERS
WHERE username like 'R%'

----QUERY TO SHOW WHO ORDERED BEFORE 2025?
SELECT*FROM ORDERS WHERE order_date< '2025-01-01'

----QUERY TO SHOW WHOSE PRODUCT PRICE IS MORE THEN 6000 IN ASCENDING ORDER?
SELECT product_name,price FROM PRODUCTS  
WHERE price> 6000
ORDER BY price ASC

----QUERY TO SHOW WHOSE PRODUCT NAME IS POWER BANK AND MOBILE?
SELECT *FROM PRODUCTS WHERE product_name = 'POWER BANK' OR product_name='MOBILE'

----QUERY TO SHOW WHOSE USERNAME LAST LETTER ENDS WITH "N"?
SELECT* FROM USERS WHERE username like '%N'

----QUERY TO SHOW STOCK QUANTITY IS LESS THAN 100 IN ASCENDING ORDER WITH RESPECT TO PRICE?
SELECT*FROM PRODUCTS
WHERE stock_quantity <100
ORDER BY price ASC

----QUERY TO SHOW WHOSE USERNAME SECOND LETTER IS "O"?
SELECT*FROM USERS WHERE username like '_O%'

----QUERY TO SHOW WHOSE USERNAME HAS 4 LETTERS?
SELECT*FROM USERS WHERE username like '____'

----QUERY TO SHOW WHOSE UNIT_PRICE IS GREATER THAN 300 RUPEES?
SELECT * FROM ORDER_ITEMS
WHERE unit_price>300
ORDER BY  order_item_ID ASC

-----QUERY TO SHOW WHO ORDERED PRODUCTS AFTER YEAR 2024?
SELECT *FROM ORDERS WHERE order_date >'2024-12-31'

-----QUERY TO SHOW USERID,USERNAME WHOSE BILLING ADDRESS IS FROM BHOPAL?
SELECT userID,username,billing_address FROM USERS 
WHERE billing_address like 'BHOPAL'

----QUERY TO SHOW WHICH ORDERID HAS MORE THAN 2 QUANTITY?
SELECT orderID,quantity FROM ORDER_ITEMS
WHERE quantity >2
ORDER BY quantity ASC